# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_bb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  data_compiler:
    build:
      context: ./backend/data_compiler
    container_name: data_compiler
    volumes:
      - ./backend/data_compiler:/app
    working_dir: /app
    depends_on:
      - redis

  data_api:
    build:
      context: ./backend/data_api
    container_name: data_api
    ports:
      - "4001:4001"
    depends_on:
      - redis

volumes:
  pgdata:
