name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: data_api_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: [6379:6379]

    env:
      MIX_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Install dependencies
        run: |
          cd backend/data_api
          mix deps.get

      - name: Create and migrate test DB
        run: |
          cd backend/data_api
          mix ecto.create

      - name: Run tests
        run: |
          cd backend/data_api
          mix test
